# Generated by Django 4.2.3 on 2023-07-04 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capaavaliacao',
            name='avaliador',
            field=models.ForeignKey(limit_choices_to={'user_type': 'avaliador'}, on_delete=django.db.models.deletion.CASCADE, related_name='capas_avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliadores',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'avaliador'}, related_name='avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='distribuidor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'distribuidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arquivoindicador',
            name='avaliador',
            field=models.ForeignKey(limit_choices_to={'user_type': 'avaliador'}, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_indicadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arquivoindicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='avaliacoes.indicador'),
        ),
    ]
